version: '3.5'
services:

  proxy:
    image: traefik:v2.4
    # Host(`proxy.local.dev`) Used by add_hosts.sh script
    container_name: proxy.local.dev
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${PWD}/config/traefik/config.yml:/etc/traefik/config.yml:ro
      - ${PWD}/config/traefik/certs:/etc/certs:ro
    networks:
      - docker-traefik-https
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - traefik.enable=true
      # Use "traefik" router configuration defined into the dynamic config file: ./traefik/config.yml
      - traefik.http.routers.traefik=true

networks:
  docker-traefik-https:
    external: true
