version: "3.5"
services:

  proxy:
    image: traefik:v2.6
    container_name: proxy.local.dev
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/config/traefik:/etc/traefik:ro
    networks:
      - docker-traefik-https
    labels:
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`proxy.local.dev`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080

networks:
  docker-traefik-https:
    external: true
