version: '3.5'

services:
  app:
    image: containous/whoami
    container_name: app
    security_opt:
      - no-new-privileges:true
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - traefik.enable=true
      # URL to reach this container
      - traefik.http.routers.app.rule=Host(`app.local.dev`)
      # Activation of TLS
      - traefik.http.routers.app.tls=true
      # If port is different than 80, use the following service:
      # - traefik.http.services.<service_name>.loadbalancer.server.port=<port>
    networks:
      - docker-traefik-https

networks:
  docker-traefik-https:
    external: true
