version: "3.7"
services:

  mysql:
    image: mysql:8.0
    # Host(`mysql.local.dev`) Used by add_hosts.sh script
    container_name: mysql.local.dev
    restart: unless-stopped
    volumes:
      - ${PWD}/config/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    ports:
      - "3306:3306"
    networks:
      - docker-traefik-https

volumes:
  mysql-data:
