version: '3.5'
services:

  redis:
    image: redis
    # Host(`redis.local.dev`) Used by add_hosts.sh script
    container_name: redis.local.dev
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass ${ROOT_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    volumes:
      - redis-data:/data
    networks:
      - docker-traefik-https
    labels:
      - traefik.enable=false

volumes:
  redis-data:
