version: "3.7"
services:

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb.local.dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .data/dynamodb:/home/dynamodblocal/data:delegated
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    networks:
      - docker-traefik-https
