services:
  dynamodb:
    image: amazon/dynamodb-local:${DYNAMODB_VERSION:-2.3.0}
    restart: unless-stopped
    volumes:
      - ./.data/dynamodb:/home/dynamodblocal/data:delegated
    ports:
      - "${FORWARD_DYNAMODB_PORT:-8000}:8000"
    working_dir: /home/dynamodblocal
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data" ]
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network
