services:
  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION:-v1.15}
    restart: unless-stopped
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailpit.rule=Host(`mailpit.test`)
      - traefik.http.routers.mailpit.tls=true
      - traefik.http.services.mailpit.loadbalancer.server.port=8025
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network
