version: "3.7"
services:

  mariadb:
    image: mariadb:10.3.11
    container_name: mariadb.local.dev
    restart: unless-stopped
    volumes:
      - ${PWD}/config/mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
      - mariadb-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${STARTUP_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p ${ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
      interval: 5s
    ports:
      - "3306:3306"
    networks:
      - docker-traefik-https

volumes:
  mariadb-data:
