services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.11.4}
    restart: on-failure
    volumes:
      - ./config/mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
      - mariadb-data:/var/lib/mysql:delegated
    ports:
      - "${FORWARD_MARIADB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "$MARIADB_PASSWORD"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "$MARIADB_STARTUP_DATABASE"
      MYSQL_USER: "$MARIADB_USERNAME"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u root" , "-p $ROOT_PASSWORD", "ping" ]
      retries: 3
      timeout: 5s
      interval: 1m
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network

volumes:
  mariadb-data:
