services:
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.7}
    restart: on-failure
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKey}
      MEILI_NO_ANALYTICS: ${MEILISEARCH_NO_ANALYTICS:-false}
    volumes:
      - meilisearch-data:/meili_data:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.meilisearch.rule=Host(`meilisearch.test`)
      - traefik.http.routers.meilisearch.tls=true
      - traefik.http.services.meilisearch.loadbalancer.server.port=7700
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      retries: 3
      timeout: 5s
      interval: 1m
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network

volumes:
  meilisearch-data:
