services:
  memcached:
    image: memcached:${MEMCACHED_VERSION:-1.6.26}
    restart: unless-stopped
    ports:
      - "${FORWARD_MEMCACHED_PORT:-11211}:11211"
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network
