version: "3.7"
services:

  redis:
    image: memcached
    container_name: memcached.local.dev
    restart: unless-stopped
    ports:
      - "11211:11211"
    networks:
      - docker-traefik-https
