version: "3.7"
services:

  minio:
    image: minio/minio:RELEASE.2022-09-07T22-25-02Z
    container_name: minio.local.dev
    restart: unless-stopped
    ports:
      - "9005:9005"
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.local.dev`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.services.minio.loadbalancer.server.port=9001
    command: server --address :9005 --console-address :9001 --compat /data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=${ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9005/minio/health/live"]
      retries: 3
      timeout: 5s
      interval: 5s
    volumes:
      - minio-data:/data:delegated
    networks:
      - docker-traefik-https

volumes:
  minio-data:
