services:
  minio:
    image: minio/minio:${MINIO_VERSION:-RELEASE.2024-03-30T09-41-56Z}
    restart: unless-stopped
    volumes:
      - minio-data:/data:delegated
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
    environment:
      MINIO_ROOT_USER: "$MINIO_USER"
      MINIO_ROOT_PASSWORD: "$MINIO_PASSWORD"
    command: server --address :9000 --console-address :8900 --compat /data
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.test`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.services.minio.loadbalancer.server.port=8900
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      retries: 3
      timeout: 5s
      interval: 5s
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network

volumes:
  minio-data:
