services:
  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}
    restart: on-failure
    volumes:
      - ./config/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql:delegated
    ports:
      - "${FORWARD_MARIADB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_PASSWORD"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "$MYSQL_STARTUP_DATABASE"
      MYSQL_USER: "$MYSQL_USERNAME"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u root" , "-p $ROOT_PASSWORD", "ping" ]
      retries: 3
      timeout: 5s
      interval: 1m
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network

volumes:
  mysql-data:
