version: "3.7"
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.local.dev
    depends_on:
      - proxy
    env_file:
      - ${PWD}/env/phpmyadmin.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.dbadmin.rule=Host(`phpmyadmin.local.dev`)
      - traefik.http.routers.dbadmin.tls=true
    networks:
      - docker-traefik-https
