version: "3.7"
services:

  postgres:
    image: postgres:14.0-alpine
    # Host(`postgres.local.dev`) Used by add_hosts.sh script
    container_name: postgres.local.dev
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_DB=${STARTUP_DATABASE}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
      interval: 5s
    ports:
      - "5432:5432"
    networks:
      - docker-traefik-https

volumes:
  postgres-data:
