services:
  redis:
    image: redis:${REDIS_VERSION:-7.0.2-alpine}
    restart: on-failure
    volumes:
      - redis-data:/data:delegated
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
      interval: 5s
    command: [ "redis-server", "--appendonly", "yes", "--requirepass $REDIS_PASSWORD" ]
    depends_on:
      traefik:
        condition: service_started
    networks:
      - docker-devel-network

volumes:
  redis-data:
