tls:
  certificates:
    # local.dev certificate
    - certFile: /etc/traefik/certs/local.dev.crt
      keyFile: /etc/traefik/certs/local.dev.key
      stores:
        - default
    # load more certificates for domains here, add all the entries you want after to generate the certificate.
    #- certFile: /etc/traefik/certs/domain1.com.crt
    #  keyFile: /etc/traefik/certs/domain1.com.key

  stores:
    default: {}
