global:
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

accessLog:
  bufferingSize: 100

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: docker-dev-https
    endpoint: unix:///var/run/docker.sock
    watch: true
  file:
    filename: /etc/traefik/config.yml
    watch: true

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          permanent: true
          to: https
          scheme: https
  https:
    address: ':443'
