global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    network: devel

  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: ERROR
  format: common

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ':443'
