version: '3.5'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.local.dev
    environment:
      - PMA_HOST=mysql.local.dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.dbadmin.rule=Host(`phpmyadmin.local.dev`)
      - traefik.http.routers.dbadmin.tls=true
    networks:
      - devel
    depends_on:
      - proxy
      - mysql
